### ISSUE TITLE
Add entry point

### ISSUE THREAD

**Issue by jugmac00** [jugmac00/workout-bot#5]
... so instead of `python3 main.py` one could use a direct command.

I am not sure what name would be fitting... something like ... :-D I'll decide later.

**Comment by eumiro** [comment]
`do_magic` sounds good, but is probably already in use.

**Comment by jugmac00** [comment]
Quoting the Zen of Python:
"Namespaces are one honking great idea—let's do more of those!"

`do_magic` was indeed available in the packages namespace....

https://github.com/jugmac00/workout-bot/blob/ee9f0c1cb23f324e7bf8e342bfbb9a7ded20d183/setup.py#L49

A word of caution - maybe `do-magic` will be deprecated once the package leaves alpha state.

Closed by #13

**Comment by jugmac00** [comment]
Oh... `-` vs `_`...
